{{- if .Values.configMaps }}
{{- range .Values.configMaps }}
{{- if .values }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  {{- range $index,$config := .values }}
  {{- range $file,$content := $config }}
  {{ $file }}: {{toYaml $content | indent 2}}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}