{{- if .Values.secrets }}
{{- range .Values.secrets }}
{{- if .values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type }}
data:
  {{- range $index,$secrets := .values }}
  {{- range $key,$value := $secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}