{{- if .Values.virtualService }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}
spec:
  hosts:
    - {{ include "app.fullname" . }}
  gateways:
  - {{ toYaml .Values.virtualService.gateway }}
  http:
    - route:
        - destination:
            host: {{ include "app.fullname" . }}
            subset: v1
{{- end }}